### ISSUE TITLE
not complete

### ISSUE THREAD

**Issue by Stefdv** [rahmathm1/pdf-viewer#1]
It seems to me that pdf-viewer.html is not complete. I miss the opening tag <polymer-element name="pdf-viewer"> ?

**Comment by rahmathm1** [comment]
@Stefdv thank you! yeah i missed the opening tag. I will add it asap.

**Comment by rahmathm1** [comment]
@Stefdv Thank you for reporting. I have fixed the issue.

**Comment by Stefdv** [comment]
Tx for the quick response. I will try to get it to work.
